use serde::Deserialize;
use std::collections::HashMap;
use std::fs;

#[derive(Deserialize)]
struct Finding {
    severity: String,
    check: String,
    endpoint: String,
    detail: String,
}

fn severity_color(s: &str) -> &str {
    match s {
        "CRITICAL" => "#7c0000",
        "HIGH"     => "#c0392b",
        "MEDIUM"   => "#e67e22",
        "LOW"      => "#2980b9",
        "INFO"     => "#27ae60",
        _          => "#555",
    }
}

fn main() {
    let data = fs::read_to_string("../findings.json")
        .expect("Could not read findings.json");
    let findings: Vec<Finding> = serde_json::from_str(&data)
        .expect("Could not parse findings.json");

    // Count by severity
    let mut counts: HashMap<&str, usize> = HashMap::new();
    for f in &findings {
        *counts.entry(f.severity.as_str()).or_insert(0) += 1;
    }

    let critical = counts.get("CRITICAL").unwrap_or(&0);
    let high     = counts.get("HIGH").unwrap_or(&0);
    let medium   = counts.get("MEDIUM").unwrap_or(&0);
    let low      = counts.get("LOW").unwrap_or(&0);
    let info     = counts.get("INFO").unwrap_or(&0);

    // Build findings rows
    let rows: String = findings.iter().map(|f| {
        let color = severity_color(&f.severity);
        format!(r#"
        <tr>
            <td><span class="badge" style="background:{color}">{sev}</span></td>
            <td>{check}</td>
            <td class="endpoint">{endpoint}</td>
            <td>{detail}</td>
        </tr>"#,
            color    = color,
            sev      = f.severity,
            check    = f.check,
            endpoint = f.endpoint,
            detail   = f.detail,
        )
    }).collect();

    let html = format!(r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>API Security Scan Report</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; background: #0f0f0f; color: #e0e0e0; margin: 0; padding: 20px; }}
  h1   {{ color: #00e5ff; border-bottom: 2px solid #00e5ff; padding-bottom: 10px; }}
  .summary {{ display: flex; gap: 16px; margin: 20px 0; flex-wrap: wrap; }}
  .card {{ padding: 16px 24px; border-radius: 8px; text-align: center; min-width: 100px; }}
  .card .num {{ font-size: 2em; font-weight: bold; }}
  .card .label {{ font-size: 0.85em; opacity: 0.8; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
  th    {{ background: #1a1a2e; color: #00e5ff; padding: 12px; text-align: left; }}
  td    {{ padding: 10px 12px; border-bottom: 1px solid #2a2a2a; vertical-align: top; }}
  tr:hover td {{ background: #1a1a1a; }}
  .badge {{ padding: 3px 10px; border-radius: 12px; font-size: 0.8em; font-weight: bold; color: white; }}
  .endpoint {{ font-family: monospace; font-size: 0.85em; color: #80cbc4; word-break: break-all; }}
  .meta {{ color: #666; font-size: 0.85em; margin-bottom: 20px; }}
</style>
</head>
<body>
<h1>🔍 API Security Scan Report</h1>
<p class="meta">Generated by api-sec-scanner &nbsp;|&nbsp; Go Engine + Python OWASP Checks + Rust Reporter</p>

<div class="summary">
  <div class="card" style="background:#7c0000"><div class="num">{critical}</div><div class="label">CRITICAL</div></div>
  <div class="card" style="background:#c0392b"><div class="num">{high}</div><div class="label">HIGH</div></div>
  <div class="card" style="background:#e67e22"><div class="num">{medium}</div><div class="label">MEDIUM</div></div>
  <div class="card" style="background:#2980b9"><div class="num">{low}</div><div class="label">LOW</div></div>
  <div class="card" style="background:#27ae60"><div class="num">{info}</div><div class="label">INFO</div></div>
  <div class="card" style="background:#333"><div class="num">{total}</div><div class="label">TOTAL</div></div>
</div>

<table>
  <thead>
    <tr><th>Severity</th><th>Check</th><th>Endpoint</th><th>Detail</th></tr>
  </thead>
  <tbody>
    {rows}
  </tbody>
</table>
</body>
</html>"#,
        critical = critical,
        high     = high,
        medium   = medium,
        low      = low,
        info     = info,
        total    = findings.len(),
        rows     = rows,
    );

    fs::write("../report.html", html).expect("Could not write report.html");
    println!("[+] Report generated → report.html ({} findings)", findings.len());
}